version: '3.8'

services:
  app:
    build:
      context: .
    image: mytheresa
    container_name: mytheresa
    ports:
      - "8080:80" # Map port 80 of the container to port 8080 on the host machine
    volumes:
      - .:/var/www # Map the current directory to the container’s working directory
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - DB_HOST=db
      - DB_DATABASE=mytheresa
      - DB_USERNAME=mytheresa
      - DB_PASSWORD=mytheresa
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mytheresa-db
    ports:
      - "3306:3306" # Map MySQL port for local access
    environment:
      MYSQL_ROOT_PASSWORD: mytheresa
      MYSQL_DATABASE: mytheresa
      MYSQL_USER: mytheresa
      MYSQL_PASSWORD: mytheresa
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
